package uz.com.task1


enum class ErrorCodes(val code: Int) {
    USER_NOT_FOUND(100),
    USER_ALREADY_EXISTS(101),
    CATEGORY_HAS_ALREADY_EXIST(201),
    CATEGORY_NOT_FOUND(200),
    PRODUCT_NOT_FOUND(300),
    USER_PAYMENT_TRANSACTION_NOT_FOUND(400),
    TRANSACTION_NOT_FOUND_EXCEPTION(500),
    PRODUCT_HAS_NOT_ENOUGH_EXCEPTION(301),
    USER_HAS_NOT_ENOUGH_BALANCE(102)
}



enum class UserRole {
    USER, ADMIN
}